cp /Development/lib/spring-framework-2.5.6/lib/antlr/antlr-2.7.6.jar ./antlr/antlr.jar
cp /Development/lib/spring-framework-2.5.6/lib/aopalliance/aopalliance.jar ./aopalliance/aopalliance.jar
cp /Development/lib/spring-framework-2.5.6/lib/aspectj/aspectjrt.jar ./aspectj/aspectjrt.jar
cp /Development/lib/spring-framework-2.5.6/lib/aspectj/aspectjweaver.jar ./aspectj/aspectjweaver.jar
cp /Development/lib/spring-framework-2.5.6/lib/cglib/cglib-nodep-2.1_3.jar ./cglib/chlib-nodep.jar
cp /Development/lib/spring-framework-2.5.6/lib/dom4j/dom4j-1.6.1.jar ./dom4j/dom4j.jar
cp /Development/lib/spring-framework-2.5.6/lib/hibernate/hibernate-annotations.jar ./hibernate/hibernate-annotations.jar
cp /Development/lib/spring-framework-2.5.6/lib/hibernate/hibernate-commons-annotations.jar ./hibernate/hibernate-commons-annotations.jar
cp /Development/lib/spring-framework-2.5.6/lib/hibernate/hibernate-entitymanager.jar ./hibernate/hibernate-entitymanager.jar
cp /Development/lib/spring-framework-2.5.6/lib/hibernate/hibernate3.jar ./hibernate/hibernate3.jar
cp /Development/lib/spring-framework-2.5.6/lib/j2ee/jta.jar ./j2ee/jta.jar
cp /Development/lib/spring-framework-2.5.6/lib/j2ee/persistence.jar ./j2ee/persistence.jar
cp /Development/lib/spring-framework-2.5.6/lib/j2ee/servlet-api.jar ./j2ee/servlet-api.jar
cp /Development/lib/spring-framework-2.5.6/lib/jakarta-commons/commons-attributes-api.jar ./jakarta-commons/commons-attributes-api.jar
cp /Development/lib/spring-framework-2.5.6/lib/jakarta-commons/commons-attributes-compiler.jar ./jakarta-commons/commons-attributes-compiler.jar
cp /Development/lib/spring-framework-2.5.6/lib/jakarta-commons/commons-beanutils.jar ./jakarta-commons/commons-beanutils.jar
cp /Development/lib/spring-framework-2.5.6/lib/jakarta-commons/commons-codec.jar ./jakarta-commons/commons-codec.jar
cp /Development/lib/spring-framework-2.5.6/lib/jakarta-commons/commons-collections.jar ./jakarta-commons/commons-collections.jar
cp /Development/lib/spring-framework-2.5.6/lib/jakarta-commons/commons-dbcp.jar ./jakarta-commons/commons-dbcp.jar
cp /Development/lib/spring-framework-2.5.6/lib/jakarta-commons/commons-digester.jar ./jakarta-commons/commons-digester.jar
cp /Development/lib/spring-framework-2.5.6/lib/jakarta-commons/commons-discovery.jar ./jakarta-commons/commons-discovery.jar
cp /Development/lib/spring-framework-2.5.6/lib/jakarta-commons/commons-fileupload.jar ./jakarta-commons/commons-fileupload.jar
cp /Development/lib/spring-framework-2.5.6/lib/jakarta-commons/commons-httpclient.jar ./jakarta-commons/commons-httpclient.jar
cp /Development/lib/spring-framework-2.5.6/lib/jakarta-commons/commons-io.jar ./jakarta-commons/commons-io.jar
cp /Development/lib/spring-framework-2.5.6/lib/jakarta-commons/commons-lang.jar ./jakarta-commons/commons-lang.jar
cp /Development/lib/spring-framework-2.5.6/lib/jakarta-commons/commons-logging.jar ./jakarta-commons/commons-logging.jar
cp /Development/lib/spring-framework-2.5.6/lib/jakarta-commons/commons-pool.jar ./jakarta-commons/commons-pool.jar
cp /Development/lib/spring-framework-2.5.6/lib/jakarta-commons/commons-validator.jar ./jakarta-commons/commons-validator.jar
cp /Development/lib/spring-framework-2.5.6/lib/junit/junit-4.4.jar ./junit/junit-4.4.jar
cp /Development/lib/spring-framework-2.5.6/lib/log4j/log4j-1.2.15.jar ./log4j/log4j.jar
cp /Development/lib/spring-framework-2.5.6/dist/modules/spring-aop.jar ./modules/spring-aop.jar
cp /Development/lib/spring-framework-2.5.6/dist/modules/spring-beans.jar ./modules/spring-beans.jar
cp /Development/lib/spring-framework-2.5.6/dist/modules/spring-context-support.jar ./modules/spring-context-support.jar
cp /Development/lib/spring-framework-2.5.6/dist/modules/spring-context.jar ./modules/spring-context.jar
cp /Development/lib/spring-framework-2.5.6/dist/modules/spring-core.jar ./modules/spring-core.jar
cp /Development/lib/spring-framework-2.5.6/dist/modules/spring-jdbc.jar ./modules/spring-jdbc.jar
cp /Development/lib/spring-framework-2.5.6/dist/modules/spring-orm.jar ./modules/spring-orm.jar
cp /Development/lib/spring-framework-2.5.6/dist/modules/spring-tx.jar ./modules/spring-tx.jar
cp /Development/lib/spring-framework-2.5.6/dist/modules/spring-web.jar ./modules/spring-web.jar
cp /Development/lib/spring-framework-2.5.6/dist/weaving/spring-agent.jar ./weaving/spring-agent.jar
cp /Development/lib/spring-framework-2.5.6/dist/weaving/spring-aspects.jar ./weaving/spring-aspects.jar
