BEGIN;

# TODO: fixed char length for UID
TRUNCATE TABLE PERMISSION;
ALTER TABLE PERMISSION
  ADD COLUMN ENTITY_ID BIGINT(20) NOT NULL DEFAULT 0,
  ADD COLUMN ENTITY_UID VARCHAR(12) NOT NULL DEFAULT '',
  ADD COLUMN ENTITY_TYPE VARCHAR(5) NOT NULL DEFAULT '',
  ADD COLUMN PRINCIPLE_ID BIGINT(20) NOT NULL DEFAULT 0,
  ADD COLUMN PRINCIPLE_UID VARCHAR(12) NOT NULL DEFAULT '',
  ADD COLUMN PRINCIPLE_TYPE VARCHAR(5) NOT NULL DEFAULT '',
  ADD COLUMN ENTRIES VARCHAR(1000) NOT NULL DEFAULT '',
  DROP COLUMN OBJECT_CLASS,
  DROP COLUMN OBJECT_UID,
  DROP COLUMN GROUP_ALLOW_VIEW,
  DROP COLUMN GROUP_ALLOW_MODIFY,
  DROP COLUMN OTHER_ALLOW_VIEW,
  DROP COLUMN OTHER_ALLOW_MODIFY,
  DROP COLUMN GROUP_ID,
  DROP COLUMN USER_ID;

COMMIT;