BEGIN;

CREATE TABLE GROUP_PRINCIPLE (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  UID varchar(12) NOT NULL,
  ENVIRONMENT_ID bigint(20) NOT NULL,
  STATUS int(11) NOT NULL,
  GROUP_ID bigint(20) NOT NULL,
  PRINCIPLE_ID bigint(20) NOT NULL DEFAULT '0',
  PRINCIPLE_UID varchar(12) NOT NULL DEFAULT '',
  PRINCIPLE_TYPE varchar(5) NOT NULL DEFAULT '',
  CREATED datetime DEFAULT NULL,
  MODIFIED datetime DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UID (UID)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

COMMIT;