BEGIN;

DROP TABLE ROLE;
DROP TABLE ROLE_ACTION;
DROP TABLE ACTION;
DROP TABLE GROUP_USER;
DROP TABLE GROUP_USER_ROLE;
DROP TABLE SCHEDULED_TASK;
DROP TABLE SITE_ALIAS;
DROP TABLE SITE;
DROP TABLE APP;
DROP TABLE SITE_APP;

COMMIT;