BEGIN;

# ITEM_VALUE_DEFINITION
ALTER TABLE ITEM_VALUE_DEFINITION ADD COLUMN FORCE_TIMESERIES BIT(1) NOT NULL DEFAULT 0;

# PERMISSION
ALTER TABLE PERMISSION ADD COLUMN ENTITY_ID BIGINT(20) NOT NULL DEFAULT 0;
ALTER TABLE PERMISSION ADD COLUMN ENTITY_UID VARCHAR(12) NOT NULL DEFAULT '';
ALTER TABLE PERMISSION ADD COLUMN ENTITY_CLASS VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE PERMISSION ADD COLUMN PRINCIPLE_ID BIGINT(20) NOT NULL DEFAULT 0;
ALTER TABLE PERMISSION ADD COLUMN PRINCIPLE_UID VARCHAR(12) NOT NULL DEFAULT '';
ALTER TABLE PERMISSION ADD COLUMN PRINCIPLE_CLASS VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE PERMISSION ADD COLUMN ENTRIES VARCHAR(1000) NOT NULL DEFAULT '';
ALTER TABLE PERMISSION DROP COLUMN OBJECT_CLASS;
ALTER TABLE PERMISSION DROP COLUMN OBJECT_UID;
ALTER TABLE PERMISSION DROP COLUMN GROUP_ALLOW_VIEW;
ALTER TABLE PERMISSION DROP COLUMN GROUP_ALLOW_MODIFY;
ALTER TABLE PERMISSION DROP COLUMN OTHER_ALLOW_VIEW;
ALTER TABLE PERMISSION DROP COLUMN OTHER_ALLOW_MODIFY;
ALTER TABLE PERMISSION DROP COLUMN GROUP_ID;
ALTER TABLE PERMISSION DROP COLUMN USER_ID;

# GROUP_PRINCIPLE
# TODO: FKs, indexes?
CREATE TABLE GROUP_PRINCIPLE (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  UID varchar(12) NOT NULL,
  ENVIRONMENT_ID bigint(20) NOT NULL,
  STATUS int(11) NOT NULL,
  GROUP_ID bigint(20) NOT NULL,
  PRINCIPLE_ID bigint(20) NOT NULL DEFAULT '0',
  PRINCIPLE_UID varchar(12) NOT NULL DEFAULT '',
  PRINCIPLE_CLASS varchar(50) NOT NULL DEFAULT '',
  ENTRIES varchar(1000) NOT NULL DEFAULT '',
  CREATED datetime DEFAULT NULL,
  MODIFIED datetime DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UID (UID)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

# PROFILE
# TODO: FKs, indexes.
ALTER TABLE PROFILE DROP COLUMN PERMISSION_ID;
ALTER TABLE PROFILE ADD COLUMN USER_ID BIGINT(20) NOT NULL DEFAULT 0;

# REMOVE TABLES
DROP TABLE ROLE;
DROP TABLE ROLE_ACTION;
DROP TABLE ACTION;
DROP TABLE GROUP_USER;
DROP TABLE GROUP_USER_ROLE;
DROP TABLE SCHEDULED_TASK;
DROP TABLE SITE_ALIAS;

COMMIT;