BEGIN;

# Create STATUS for all tables
ALTER TABLE ACTION ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE ALGORITHM ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE API_VERSION ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE APP ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE DATA_CATEGORY ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE ENVIRONMENT ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE GROUPS ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE GROUP_USER ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE ITEM ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE ITEM_DEFINITION ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE ITEM_VALUE ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE ITEM_VALUE_DEFINITION ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE PERMISSION ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE PROFILE ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE ROLE ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE SITE ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE SITE_APP ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;
ALTER TABLE VALUE_DEFINITION ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1;

COMMIT;
