BEGIN;

# Drop CLASS_ALIAS
DROP TABLE amee.CLASS_ALIAS;

# Drop SKIN_IMPORT
DROP TABLE amee.SKIN_IMPORT;

# Drop SKIN
DROP TABLE amee.SKIN;

# Drop VERSION columns
ALTER TABLE amee.ACTION DROP COLUMN VERSION;
ALTER TABLE amee.APP DROP COLUMN VERSION;
ALTER TABLE amee.ENVIRONMENT DROP COLUMN VERSION;
ALTER TABLE amee.GROUPS DROP COLUMN VERSION;
ALTER TABLE amee.GROUP_USER DROP COLUMN VERSION;
ALTER TABLE amee.PERMISSION DROP COLUMN VERSION;
ALTER TABLE amee.ROLE DROP COLUMN VERSION;
ALTER TABLE amee.SITE DROP COLUMN VERSION;
ALTER TABLE amee.SCHEDULED_TASK DROP COLUMN VERSION;
ALTER TABLE amee.SITE_ALIAS DROP COLUMN VERSION;
ALTER TABLE amee.SITE_APP DROP COLUMN VERSION;
ALTER TABLE amee.TARGET DROP COLUMN VERSION;
ALTER TABLE amee.USER DROP COLUMN VERSION;

# Alter USER
ALTER TABLE amee.USER MODIFY COLUMN PASSWORD VARCHAR(40);
ALTER TABLE amee.USER DROP COLUMN SUPER_USER;
ALTER TABLE amee.USER ADD COLUMN NICK_NAME VARCHAR(255) default NULL;
ALTER TABLE amee.USER ADD COLUMN LOCATION VARCHAR(255) default NULL;
ALTER TABLE amee.USER ADD COLUMN USER_TYPE int(11) default NULL;
ALTER TABLE amee.USER ADD COLUMN API_VERSION_ID bigint(20) default NULL;
ALTER TABLE amee.USER ADD INDEX API_VERSION_ID_IND USING BTREE(API_VERSION);

# Alter ITEM
ALTER TABLE amee.ITEM CHANGE VALID_FROM START_DATE DATETIME;
ALTER TABLE amee.ITEM CHANGE COLUMN AMOUNT_PER_MONTH AMOUNT DATETIME DEFAULT NULL;
ALTER TABLE amee.ITEM ADD INDEX START_DATE_IND USING BTREE(START_DATE);
ALTER TABLE amee.ITEM ADD INDEX END_DATE_IND USING BTREE(END_DATE);

# Alter ALGORITHM
ALTER TABLE amee.ALGORITHM MODIFY COLUMN ITEM_DEFINITION_ID BIGINT (20) NULL;
ALTER TABLE amee.ALGORITHM ADD COLUMN TYPE VARCHAR(3) NOT NULL;
ALTER TABLE amee.ALGORITHM ADD COLUMN ALGORITHM_CONTEXT_ID bigint(20) default NULL;
ALTER TABLE amee.ALGORITHM ADD INDEX ALGORITHM_CONTEXT_ID_IND USING BTREE(ALGORITHM_CONTEXT_ID);

# Create API_VERSION
CREATE TABLE  amee.API_VERSION (
  ID bigint(20) NOT NULL auto_increment,
  CREATED datetime default NULL,
  MODIFIED datetime default NULL,
  UID varchar(12) NOT NULL,
  VERSION varchar(3) default NULL,
  PRIMARY KEY  (ID),
  UNIQUE KEY UID (UID)
) 

# Alter ENVIRONMENT
ALTER TABLE amee.ENVIRONMENT ADD COLUMN ITEMS_PER_FEED int(11) NOT NULL;
ALTER TABLE amee.ENVIRONMENT ADD COLUMN OWNER varchar(255) default NULL;

# Alter ITEM_VALUE
ALTER TABLE amee.ITEM_VALUE ADD COLUMN UNIT varchar(255) default NULL;
ALTER TABLE amee.ITEM_VALUE ADD COLUMN PER_UNIT varchar(255) default NULL;

# Alter ITEM_VALUE_DEFINITION
ALTER TABLE amee.ITEM_VALUE_DEFINITION ADD COLUMN UNIT varchar(255) default NULL;
ALTER TABLE amee.ITEM_VALUE_DEFINITION ADD COLUMN PER_UNIT varchar(255) default NULL;
ALTER TABLE amee.ITEM_VALUE_DEFINITION ADD COLUMN ALIASED_TO bigint(20) default NULL;
ALTER TABLE amee.ITEM_VALUE_DEFINITION ADD INDEX ALIASED_TO_IND USING BTREE(ALIASED_TO);

# Create ITEM_VALUE_DEFINITION_API_VERSION
CREATE TABLE  amee.ITEM_VALUE_DEFINITION_API_VERSION (
  ITEM_VALUE_DEFINITION_ID bigint(20) NOT NULL,
  API_VERSION_ID bigint(20) NOT NULL,
  PRIMARY KEY  USING BTREE (ITEM_VALUE_DEFINITION_ID,API_VERSION_ID),
  KEY API_VERSION_ID_IND (API_VERSION_ID),
  KEY ITEM_VALUE_DEFINITION_ID_IND (ITEM_VALUE_DEFINITION_ID)
) 

COMMIT;