BEGIN;

### PERMISSION

# User (load) to Environment
INSERT INTO PERMISSION (UID, ENVIRONMENT_ID, STATUS, ENTITY_ID, ENTITY_UID, ENTITY_TYPE, PRINCIPLE_ID, PRINCIPLE_UID, PRINCIPLE_TYPE, ENTRIES, CREATED, MODIFIED)
  VALUES ('DA2C6DA71AA6', 2, 1, 2, '5F5887BCF726', 'ENV', 45, 'DB2C6DA7EAA7', 'USR', '{"entries":[{"value":"view"}]}', now(), now());

# Group (amee) to Environment
INSERT INTO PERMISSION (UID, ENVIRONMENT_ID, STATUS, ENTITY_ID, ENTITY_UID, ENTITY_TYPE, PRINCIPLE_ID, PRINCIPLE_UID, PRINCIPLE_TYPE, ENTRIES, CREATED, MODIFIED)
  VALUES ('DA2C6DA71BB6', 2, 1, 2, '5F5887BCF726', 'ENV', 5, 'AC65FFA5F9D9', 'GRP', '{"entries":[{"value":"view"},{"value":"create.pr"}]}', now(), now());

# Group (Administrators) to Environment
INSERT INTO PERMISSION (UID, ENVIRONMENT_ID, STATUS, ENTITY_ID, ENTITY_UID, ENTITY_TYPE, PRINCIPLE_ID, PRINCIPLE_UID, PRINCIPLE_TYPE, ENTRIES, CREATED, MODIFIED)
  VALUES ('DA2C6DA71BB7', 2, 1, 2, '5F5887BCF726', 'ENV', 4, '2E4FE8076E5C', 'GRP', '{"entries":[{"value":"view"},{"value":"view", "status":"deprecated"},{"value":"create"},{"value":"modify"},{"value":"delete"}]}', now(), now());

# User (floppyv2) to Data Category
INSERT INTO PERMISSION (UID, ENVIRONMENT_ID, STATUS, ENTITY_ID, ENTITY_UID, ENTITY_TYPE, PRINCIPLE_ID, PRINCIPLE_UID, PRINCIPLE_TYPE, ENTRIES, CREATED, MODIFIED)
  VALUES ('DA2AADA71BB7', 2, 1, 63, '2957AE9B6E6B', 'DC', 588, '743290226F65', 'USR', '{"entries":[{"value":"own"}]}', now(), now());

### GROUP_PRINCIPLE

# User (load) in Group (amee)
INSERT INTO GROUP_PRINCIPLE (UID, ENVIRONMENT_ID, STATUS, GROUP_ID, PRINCIPLE_ID, PRINCIPLE_UID, PRINCIPLE_TYPE, CREATED, MODIFIED)
  VALUES ('DA2C6CC71AA7', 2, 1, 5, 45, 'DB2C6DA7EAA7', 'USR', now(), now());

# User (floppy) in Group (amee)
INSERT INTO GROUP_PRINCIPLE (UID, ENVIRONMENT_ID, STATUS, GROUP_ID, PRINCIPLE_ID, PRINCIPLE_UID, PRINCIPLE_TYPE, CREATED, MODIFIED)
  VALUES ('DA2C6CC71BA7', 2, 1, 5, 61, '1A6307E2B531', 'USR', now(), now());

# User (floppyv2) in Group (amee)
INSERT INTO GROUP_PRINCIPLE (UID, ENVIRONMENT_ID, STATUS, GROUP_ID, PRINCIPLE_ID, PRINCIPLE_UID, PRINCIPLE_TYPE, CREATED, MODIFIED)
  VALUES ('DA2C6CC71CA7', 2, 1, 5, 588, '743290226F65', 'USR', now(), now());

# User (admin) in Group (Administrators)
INSERT INTO GROUP_PRINCIPLE (UID, ENVIRONMENT_ID, STATUS, GROUP_ID, PRINCIPLE_ID, PRINCIPLE_UID, PRINCIPLE_TYPE, CREATED, MODIFIED)
  VALUES ('DA2C6CC71BA1', 2, 1, 4, 6, '3D7D11293ECA', 'USR', now(), now());

# User (adminv2) in Group (Administrators)
INSERT INTO GROUP_PRINCIPLE (UID, ENVIRONMENT_ID, STATUS, GROUP_ID, PRINCIPLE_ID, PRINCIPLE_UID, PRINCIPLE_TYPE, CREATED, MODIFIED)
  VALUES ('DA2C6CC71CA2', 2, 1, 4, 846, '9D376C97D76F', 'USR', now(), now());

COMMIT;
