BEGIN;

# SITE_APP
UPDATE SITE_APP SET SKIN_PATH = 'client-default' WHERE SKIN_PATH = 'default.client.skin';
UPDATE SITE_APP SET SKIN_PATH = 'admin-default' WHERE SKIN_PATH = 'default.admin.skin';
UPDATE SITE_APP SET SKIN_PATH = 'app-admin' WHERE SKIN_PATH = 'app.admin.skin';
UPDATE SITE_APP SET SKIN_PATH = 'cache-admin' WHERE SKIN_PATH = 'cache.skin';
DELETE FROM SITE_APP WHERE APP_ID IN (SELECT ID FROM APP WHERE NAME = 'My Account');
DELETE FROM SITE_APP WHERE APP_ID IN (SELECT ID FROM APP WHERE NAME = 'Skin Administration');
DELETE FROM SITE_APP WHERE SKIN_PATH = 'site.admin.skin';

# ENVIRONMENT 
UPDATE ENVIRONMENT SET ITEMS_PER_FEED = 10;
UPDATE ENVIRONMENT SET OWNER = '';

# APP
DELETE FROM APP WHERE NAME = 'My Account';
DELETE FROM APP WHERE NAME = 'Skin Administration';

# SITE
UPDATE SITE SET SECURE_AVAILABLE = 0;

# ITEM
UPDATE ITEM SET START_DATE = CREATED WHERE START_DATE IS NULL AND TYPE='DI';
UPDATE ITEM SET AMOUNT = NULL WHERE TYPE='DI';

# ALGORITHM
UPDATE ALGORITHM set TYPE='AL';

# API_VERSION
INSERT INTO API_VERSION (ID, CREATED, MODIFIED, UID, VERSION)
VALUES	('1', SYSDATE(), SYSDATE(), '655B1AD17733', '1.0'),
 		('2', SYSDATE(), SYSDATE(), '4D2BAA6BB1BE', '2.0');

# USER
UPDATE USER set API_VERSION_ID = 1;
UPDATE USER SET STATUS = 0;
UPDATE USER SET USER_TYPE = 0;
UPDATE USER SET USER_TYPE = 3 WHERE USERNAME = 'root';

COMMIT;