CREATE TABLE `RETURN_VALUE_DEFINITION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UID` varchar(12) NOT NULL,
  `CREATED` datetime DEFAULT NULL,
  `MODIFIED` datetime DEFAULT NULL,
  `ENVIRONMENT_ID` bigint(20) NOT NULL,
  `ITEM_DEFINITION_ID` bigint(20) NOT NULL,
  `VALUE_DEFINITION_ID` bigint(20) NOT NULL,
  `UNIT` varchar(255) DEFAULT NULL,
  `PER_UNIT` varchar(255) DEFAULT NULL,
  `STATUS` int(11) NOT NULL,
  `IS_DEFAULT` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UID` (`UID`)
)