# Drop CLASS_ALIAS
DROP TABLE amee.CLASS_ALIAS;

# Drop SKIN_IMPORT
DROP TABLE amee.SKIN_IMPORT;

# Drop SKIN
DROP TABLE amee.SKIN;

# Drop VERSION columns
ALTER TABLE amee.ACTION DROP COLUMN VERSION;
ALTER TABLE amee.APP DROP COLUMN VERSION;
ALTER TABLE amee.ENVIRONMENT DROP COLUMN VERSION;
ALTER TABLE amee.GROUPS DROP COLUMN VERSION;
ALTER TABLE amee.GROUP_USER DROP COLUMN VERSION;
ALTER TABLE amee.PERMISSION DROP COLUMN VERSION;
ALTER TABLE amee.ROLE DROP COLUMN VERSION;
ALTER TABLE amee.SITE DROP COLUMN VERSION;
ALTER TABLE amee.SCHEDULED_TASK DROP COLUMN VERSION;
ALTER TABLE amee.SITE_ALIAS DROP COLUMN VERSION;
ALTER TABLE amee.SITE_APP DROP COLUMN VERSION;
ALTER TABLE amee.TARGET DROP COLUMN VERSION;
ALTER TABLE amee.USER DROP COLUMN VERSION;

# Alter USER
ALTER TABLE amee.USER MODIFY COLUMN PASSWORD VARCHAR(40);
ALTER TABLE amee.USER DROP COLUMN SUPER_USER;
ALTER TABLE amee.USER ADD COLUMN NICK_NAME VARCHAR(255) default NULL;
ALTER TABLE amee.USER ADD COLUMN LOCATION VARCHAR(255) default NULL;
ALTER TABLE amee.USER ADD COLUMN USER_TYPE int(11) default NULL;
ALTER TABLE amee.USER ADD COLUMN API_VERSION bigint(20) default NULL;
ALTER TABLE amee.USER ADD INDEX USER_API_VERSION_IDX USING BTREE(API_VERSION);

# Alter ITEM
ALTER TABLE amee.ITEM DROP COLUMN START_DATE;
ALTER TABLE amee.ITEM CHANGE VALID_FROM START_DATE DATETIME; (REMOVE ONE OF THESE)
ALTER TABLE amee.ITEM DROP COLUMN AMOUNT_PER_MONTH; (SHOULD BE RENAME)
MISSING - Drop End
MISSING -  KEY `START_DATE_IND` USING BTREE (`START_DATE`),
MISSING -  KEY `END_DATE_IND` USING BTREE (`END_DATE`),

# Alter ALGORITHM
ALTER TABLE amee.ALGORITHM MODIFY COLUMN ITEM_DEFINITION_ID BIGINT (20) NULL;
ALTER TABLE amee.ALGORITHM ADD COLUMN TYPE VARCHAR(3) NOT NULL;
ALTER TABLE amee.ALGORITHM ADD COLUMN ALGORITHM_CONTEXT_ID bigint(20) default NULL;
MISSING - KEY `FKB388C44F1192B6C4` (`ALGORITHM_CONTEXT_ID`)

# Create API_VERSION
MISSING - Create API_VERSION

# Alter ENVIRONMENT
MISSING - ENVIRONMENT Create ITEMS_PER_FEED / OWNER

# Alter ITEM_VALUE
MISSING - Create UNIT
MISSING - Create PER_UNIT

# Alter ITEM_VALUE_DEFINITION
MISSING - PER_UNIT
MISSING - UNIT
MISSING - ALIASED_TO
MISSING - KEY `FK21D1A8ADED3FF633` (`ALIASED_TO`),

# Create ITEM_VALUE_DEFINITION_API_VERSION
MISSING - Create ITEM_VALUE_DEFINITION_API_VERSION

# -----------------------------------------------------------------------------------------------------

# ENVIRONMENT 
UPDATE amee.ENVIRONMENT SET ITEMS_PER_FEED = 10;
UPDATE amee.ENVIRONMENT SET OWNER = '';

# APP
UPDATE amee.APP SET TARGET_BUILDER = '';

# SITE
UPDATE amee.SITE SET SERVER_ADDRESS = '', SERVER_PORT = '', SERVER_SCHEME = '', SECURE_AVAILABLE = 0;

# ITEM
UPDATE amee.ITEM SET START_DATE = CREATED WHERE START_DATE IS NULL AND TYPE='DI';
UPDATE amee.ITEM SET AMOUNT = AMOUNT_PER_MONTH WHERE TYPE='PI';
UPDATE amee.ITEM SET AMOUNT = null WHERE TYPE='DI';

# ALGORITHM
UPDATE amee.ALGORITHM set TYPE='AL';

# TARGET
DELETE FROM amee.TARGET WHERE TARGET='skinRenderResource';
INSERT INTO amee.TARGET
(ID, UID, NAME, DESCRIPTION, URI_PATTERN, TARGET, DEFAULT_TARGET, DIRECTORY_TARGET, ENABLED, CREATED, MODIFIED, APP_ID, TYPE)
VALUES ('67', 'F613C476EADD', 'Algorithm Contexts Resource', '', '/{environmentUid}/algorithmContexts',
        'algorithmContextsResource', b'00000000', b'00000000', b'00000001', SYSDATE(), SYSDATE(), '4', '0'),
       ('68', '21F188A4937F', 'Algorithm Context Resource', '', '/{environmentUid}/algorithmContexts/{algorithmContentUid}',
        'algorithmContextResource', b'00000000', b'00000000', b'00000001', SYSDATE(), SYSDATE(), '4', '0');

# API_VERSION
INSERT INTO amee.API_VERSION (ID, CREATED, MODIFIED, UID, VERSION)
VALUES	('1', SYSDATE(), SYSDATE(), '655B1AD17733', '1.0'),
 		('2', SYSDATE(), SYSDATE(), '4D2BAA6BB1BE', '2.0');

# USER
UPDATE amee.USER set API_VERSION = 1;
UPDATE amee.USER SET LOCATION = '';
UPDATE amee.USER SET NICK_NAME = '';
UPDATE amee.USER SET STATUS = 0;
UPDATE amee.USER SET USER_TYPE = 0;
UPDATE amee.USER SET USER_TYPE = 3 WHERE USERNAME = 'root';

# ITEM_VALUE_DEFINITION
update ITEM_VALUE_DEFINITION set UNIT='km', PER_UNIT='year' where PATH='distance';
update ITEM_VALUE_DEFINITION set PER_UNIT='year' where PATH='kWh';